### ISSUE TITLE
2 little boxes remove

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#120] opened 2020-06-10 20:36 UTC
Display has two little boxes on top left. Please remove these boxes.

**Comment by danielruss** [comment] 2020-06-15 13:42
I don't see the boxes, please send me your browser info (i.e chrome on PC) what URL (i.e. did you use danielruss.github.io/simpletest) and if possible a screenshot.

**Comment by ruggz13** [comment] 2020-06-15 15:49
Cannot see two boxes in testing the modules...I used to see them in the Connect PWA, but that is a Connect problem, not Quest

**Comment by ashreves** [comment] 2020-06-15 18:23
I used Chrome on a PC
<img width="652" alt="Littleboxes" src="https://user-images.githubusercontent.com/54043164/84692410-d1f5ae80-af13-11ea-92ce-1ad060f2a3fa.PNG">


URL was https://danielruss.github.io/simpletest/index2.html

**Comment by ruggz13** [comment] 2020-06-16 16:12
Any idea what is causing this @danielruss ?

**Comment by danielruss** [comment] 2020-06-16 16:15
I am unable to reproduce the boxes.  Maybe this was a problem with the markdown at one point?  I have run this multiple times on chrome, edge, and firefox.  I'll try on a linux box later and see if I can reproduce the error.

**Comment by ruggz13** [comment] 2020-06-16 16:16
It might be a PC thing, because I noticed these two boxes on Bhaumik's machine and he uses PC

**Comment by danielruss** [comment] 2020-06-16 16:19
Maybe you could walk through with Alaina and have her use the developer tools to see what element the boxes are?  (inspect the boxes)

**Comment by ruggz13** [comment] 2020-06-16 16:43
@danielruss @ashreves We just had a call and the boxes were gone... so unless this pops up again I'm going to close this for now

**Closed by ruggz13** 2020-06-16 16:43 UTC
Labels: Engineering, Style, bug
