### ISSUE TITLE
Google maps functionality

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#119] opened 2020-06-10 19:27 UTC
Is Google maps is not being used to facilitate here? Is that going to be added later?

See ALTADDRESS2

**Comment by danielruss** [comment] 2020-06-16 17:21
duplicate of #43

**Comment by danielruss** [comment] 2020-06-25 22:21
@bhaumik55231 Do you have any advice on how to handle this?

**Comment by hzhao392** [comment] 2020-09-22 18:52
will be a PWA question

**Closed by hzhao392** 2020-09-22 18:52 UTC
Labels: Questionnaire User, enhancement
